### ISSUE TITLE
Wrong screenshot?

### ISSUE THREAD

**Issue by sergiomarotco** [gattjoe/TlsTestGate#15]
in https://marketplace.visualstudio.com/items?itemName=gattjoe.TlsTestGate i see:
![image](https://user-images.githubusercontent.com/29877074/163319786-0ddddb52-8258-4a33-bb32-ba8c03baa8e5.png)
in [manual](https://github.com/MetLife/TlsTestGate#yaml-sample) i see:
`steps:
- task: JoeGatt.TlsTestGate.custom-build-release-task.TlsTestGate@1
  displayName: 'github.com SSL/TLS Test Gate'
  inputs:
    baseURL: github.com
    port: 443
    dnsserver: 8.8.8.8
    **failBuild**: true`

**Comment by gattjoe** [comment]
yep, wrong screenshot, good catch.  will have to update

**Comment by gattjoe** [comment]
fixed with PR #16
